### ISSUE TITLE
Global variable on PHP contact file

### ISSUE THREAD

**Issue by rafa-acioly** [sitecake/agency-template#1]
In the main file on contact me file there is of insecure lines of code, e.g:

> using global variable without filter

https://github.com/sitecake/agency-template/blob/master/mail/contact_me.php#L13

can i send a `PR` to fix it?

**Comment by sitecake** [comment]
Sure. Please.

**Comment by rafa-acioly** [comment]
sended https://github.com/sitecake/agency-template/pull/2

**Comment by rafa-acioly** [comment]
i've created another `PR` to handle `CSRF` as well https://github.com/sitecake/agency-template/pull/3

**Comment by predragleka** [comment]
Solved with PR #3
